version: '3'
services:
  csv_server:
    build:
      dockerfile: Dockerfile
      context: ./csvServer
    environment:
      - PORT=9001
  data_server:
    build:
      dockerfile: Dockerfile
      context: ./dataServer
    environment:
      - CSV_HOST_PORT=9001
    ports:
      - '80:80'